My First Pytorch notebook

In [39]:
import torch

In [40]:
x=torch.rand(3,3)

In [41]:
import pandas as pd

In [42]:
print(x)

tensor([[0.4808, 0.5772, 0.8880],
        [0.0652, 0.6066, 0.7738],
        [0.6166, 0.3378, 0.0688]])


In [43]:
y=pd.DataFrame(x)
y

0         1         2
0  0.480754  0.577205  0.888027
1  0.065247  0.606604  0.773815
2  0.616608  0.337835  0.068829

In [44]:
print(torch.__version__)

2.2.1+cu121


Deep Learning is a subset of machine learning

Introduction to Tensors

In [45]:
scalr = torch.tensor(x)
scalr

<ipython-input-45-47c3021c4d95>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  scalr = torch.tensor(x)


tensor([[0.4808, 0.5772, 0.8880],
        [0.0652, 0.6066, 0.7738],
        [0.6166, 0.3378, 0.0688]])

In [46]:
scalar = torch.tensor([7,7])
scalar

tensor([7, 7])

In [47]:
type(scalar)

torch.Tensor

In [48]:
seven = torch.tensor(43)
type(seven.item())

int

In [49]:
import numpy as np

In [50]:
seven.numpy()

array(43)

In [51]:
scalar.numpy()

array([7, 7])

In [52]:
scalr.numpy()

array([[0.48075438, 0.57720494, 0.888027  ],
       [0.06524664, 0.6066036 , 0.77381545],
       [0.61660755, 0.3378349 , 0.06882936]], dtype=float32)

In [53]:
scalar.ndim

1

In [54]:
scalr.ndim

2

In [55]:
scalr.shape

torch.Size([3, 3])

In [56]:
seven.shape

torch.Size([])

In [57]:
randomTensor = torch.rand([5,6,4,4,3,5])

In [58]:
randomTensor.shape

torch.Size([5, 6, 4, 4, 3, 5])

In [59]:
randomTensor.ndim

6

In [60]:
randomTensor

tensor([[[[[[9.7521e-01, 5.3913e-01, 9.7885e-01, 6.5641e-01, 9.2666e-01],
            [6.6237e-01, 6.6926e-01, 3.7552e-01, 2.2337e-01, 2.3611e-01],
            [4.5416e-01, 8.8771e-01, 4.6794e-01, 2.1045e-01, 4.2919e-01]],

           [[3.0930e-01, 7.7183e-01, 3.7534e-01, 5.6126e-01, 5.3164e-01],
            [8.8063e-01, 3.2517e-01, 3.5457e-01, 4.2957e-01, 8.5349e-01],
            [5.9529e-01, 2.6925e-02, 3.1115e-01, 1.3456e-01, 9.0148e-01]],

           [[7.5968e-02, 5.3772e-01, 3.9349e-01, 2.5296e-01, 2.5757e-01],
            [8.4882e-01, 7.7327e-01, 8.1113e-01, 4.6902e-01, 8.3750e-01],
            [5.7340e-01, 6.0102e-01, 4.1988e-01, 5.3600e-01, 8.9467e-01]],

           [[7.8004e-01, 4.6351e-01, 9.8923e-02, 3.3709e-01, 3.7027e-02],
            [4.3605e-01, 8.3834e-01, 2.6535e-01, 4.8176e-02, 8.5461e-01],
            [3.5892e-01, 3.7642e-01, 4.8668e-01, 8.3531e-02, 1.8914e-01]]],


          [[[7.2814e-01, 6.3113e-01, 3.8979e-01, 2.6008e-01, 1.0325e-01],
            [9.1336e-01, 6.0

In [61]:
import matplotlib.pyplot as plt

In [62]:
zero = torch.zeros(3,3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [63]:
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [64]:
zero + ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [65]:
torch.ones_like(scalr) ## takes an input tensor and return one unit tensor for that input size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [67]:
torch.nn.init.ones_(w)
w

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [68]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
torch.arange(1,11,2)

tensor([1, 3, 5, 7, 9])

In [70]:
torch.full_like(scalr, fill_value=3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

tensor creattion **args

- default dtype = None/float32
- other dtypes are complex16-32/float16-32-62 & more
- device = cpu/cuda** tensors not on same device wont work together
- requires_grad =T/F pytorch calcluates gradient? for tensor after numerical calculations

In [71]:
scalar16 = scalar.type(torch.float16)

In [72]:
scalar16

tensor([7., 7.], dtype=torch.float16)

In [73]:
scalar16*scalar

tensor([49., 49.], dtype=torch.float16)

In [74]:
torch.zeros(3,3) * torch.ones(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [75]:
three = torch.full_like(torch.empty(3,3), fill_value=3)
three * three

tensor([[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]])

In [76]:
## torch.rand(3,3,device="cuda")

In [77]:
new = torch.tensor([1,2,3])
new

tensor([1, 2, 3])

In [78]:
new + 10

tensor([11, 12, 13])

In [79]:
new + (-2)

tensor([-1,  0,  1])

In [80]:
new * new

tensor([1, 4, 9])

In [81]:
new / torch.rand(1,3)

tensor([[2.6014, 2.2953, 3.7415]])

In [82]:
torch.multiply(new,new)

tensor([1, 4, 9])

In [83]:
first = torch.full_like(torch.empty(3,3), fill_value=3)
second = torch.full_like(torch.empty(3,3), fill_value=4)
third = torch.full_like(torch.empty(3,4), fill_value=3)

torch.multiply(first, second)

tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])

In [84]:
torch.matmul(first, second)

tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]])

In [94]:
# torch.multiply(first, third)

In [86]:
torch.matmul(first, third)

tensor([[27., 27., 27., 27.],
        [27., 27., 27., 27.],
        [27., 27., 27., 27.]])

In [87]:
torch.matmul(torch.tensor([1,2,3]), torch.tensor([1,2,3]))  ## matmuls doubles as matrix mutliplication and vector dot product

tensor(14)

In [89]:
fourth = torch.full_like(torch.empty(4,3), fill_value=5)

In [91]:
fourth.T

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [96]:
torch.mm(second, fourth.T)

tensor([[60., 60., 60., 60.],
        [60., 60., 60., 60.],
        [60., 60., 60., 60.]])

current timestamp - 2:50:00

In [128]:
first = torch.rand(4, 4) * (11 - 1) + 1

In [146]:
first

tensor([[ 9.9818, 10.1899,  8.6344,  3.7334],
        [ 7.5663,  8.0053,  4.2280,  1.8220],
        [10.4300,  5.9147,  2.3281,  9.3560],
        [ 8.9211, 10.1987, 10.4366,  6.5863]])

In [147]:
first.matrix_power(2)

tensor([[300.0994, 272.4329, 188.3362, 161.2047],
        [196.4490, 184.7749, 128.0360,  94.3915],
        [256.6114, 262.8193, 218.1293, 133.1198],
        [333.8276, 301.4512, 213.1859, 192.9129]])

In [130]:
first.max()

tensor(10.4366)

In [131]:
first.min()

tensor(1.8220)

In [132]:
first.sum()

tensor(118.3328)

In [133]:
first.mean()

tensor(7.3958)

In [134]:
first.floor()

tensor([[ 9., 10.,  8.,  3.],
        [ 7.,  8.,  4.,  1.],
        [10.,  5.,  2.,  9.],
        [ 8., 10., 10.,  6.]])

In [135]:
first.ceil()

tensor([[10., 11.,  9.,  4.],
        [ 8.,  9.,  5.,  2.],
        [11.,  6.,  3., 10.],
        [ 9., 11., 11.,  7.]])

In [136]:
first.round()

tensor([[10., 10.,  9.,  4.],
        [ 8.,  8.,  4.,  2.],
        [10.,  6.,  2.,  9.],
        [ 9., 10., 10.,  7.]])

In [137]:
torch.mean(first)

tensor(7.3958)

In [139]:
first.argmin(), first.argmax()  ## returns index value of arg

(tensor(7), tensor(14))

In [151]:
first.flatten()[14], first.flatten()[7]

(tensor(10.4366), tensor(1.8220))