In [1]:
import torch

In [3]:
x = torch.arange(1,7)
x

tensor([1, 2, 3, 4, 5, 6])

In [14]:
x = x.reshape(1,6)
x

tensor([[1, 2, 3, 4, 5, 6]])

In [15]:
x = x.reshape(6,1)
x

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [16]:
x = x.reshape(2,3)
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
x[1]

tensor([4, 5, 6])

In [22]:
## x[2]

In [23]:
x.shape

torch.Size([2, 3])

In [26]:
z = x.view(1,6)
z.shape

torch.Size([1, 6])

Views share memory with original tensor. This means change in z is change in x.

In [30]:
stackOfX = torch.stack([x,x,x])
stackOfX

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [33]:
stackOfX = torch.stack([x,z.view(2,3),x,z.view(2,3)])
stackOfX

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [34]:
stackOfX.shape

torch.Size([4, 2, 3])

In [39]:
stackOfX = torch.hstack([x,z.view(2,3),x,z.view(2,3)])
stackOfX, stackOfX.shape

(tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
         [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]]),
 torch.Size([2, 12]))

In [40]:
stackOfX = torch.vstack([x,z.view(2,3),x,z.view(2,3)])
stackOfX, stackOfX.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [1, 2, 3],
         [4, 5, 6],
         [1, 2, 3],
         [4, 5, 6],
         [1, 2, 3],
         [4, 5, 6]]),
 torch.Size([8, 3]))

In [43]:
stackOfX = torch.stack([x,x,x,x], dim=0)
stackOfX, stackOfX.shape

(tensor([[[1, 2, 3],
          [4, 5, 6]],
 
         [[1, 2, 3],
          [4, 5, 6]],
 
         [[1, 2, 3],
          [4, 5, 6]],
 
         [[1, 2, 3],
          [4, 5, 6]]]),
 torch.Size([4, 2, 3]))

In [44]:
stackOfX = torch.stack([x,x,x,x], dim=1)
stackOfX, stackOfX.shape

(tensor([[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],
 
         [[4, 5, 6],
          [4, 5, 6],
          [4, 5, 6],
          [4, 5, 6]]]),
 torch.Size([2, 4, 3]))

In [48]:
stackOfX = torch.stack([x,x,x,x], dim=2)
stackOfX, stackOfX.shape, stackOfX.mT, stackOfX.mT.shape

(tensor([[[1, 1, 1, 1],
          [2, 2, 2, 2],
          [3, 3, 3, 3]],
 
         [[4, 4, 4, 4],
          [5, 5, 5, 5],
          [6, 6, 6, 6]]]),
 torch.Size([2, 3, 4]),
 tensor([[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],
 
         [[4, 5, 6],
          [4, 5, 6],
          [4, 5, 6],
          [4, 5, 6]]]),
 torch.Size([2, 4, 3]))

In [64]:
x = x.reshape(1,1,1,6)  ## remove single dimensions from tensor?
x

tensor([[[[1, 2, 3, 4, 5, 6]]]])

In [65]:
x = torch.squeeze(x)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6]), torch.Size([6]))

In [69]:
rz = torch.rand(3,1,4,1,6)

In [71]:
rz = rz.unsqueeze(-1)
rz.shape

torch.Size([3, 1, 4, 1, 6, 1])

In [94]:
rz = rz.permute(5,1,3,0,2,4)
rz.shape

torch.Size([1, 1, 1, 3, 4, 6])

In [95]:
rz.permute(*torch.arange(rz.ndim - 1, -1, -1)).shape

torch.Size([6, 4, 3, 1, 1, 1])

In [98]:
torch.arange(rz.ndim - 1, -1, -1)

tensor([5, 4, 3, 2, 1, 0])

In [101]:
%%time
rz = rz.permute(5,1,3,0,2,4)

CPU times: user 147 µs, sys: 0 ns, total: 147 µs
Wall time: 154 µs


Remember that permuted tensors share memory with original tensor.

This means that change in one would be reflected in other as well.

In [102]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [123]:
x[0][2][2], x[:,2,2], x[:,:,2]

(tensor(9), tensor([9]), tensor([[3, 6, 9]]))

In [127]:
f = x.flatten()
f, f[-1]

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor(9))

numpy to tensor => `torch.from_numpy(ndararray)`

tensor to numpy => `torch.Tensor.numpy()`

dtypes mismatch might occur. np default dtype is float64 and torch reflects it it coverted tensor unless specified.

memory is not shared here unlike view.

In [151]:
torch.random.manual_seed(43)
torch.rand([2,3]) ,torch.rand([3,2])

(tensor([[0.4540, 0.1965, 0.9210],
         [0.3462, 0.1481, 0.0858]]),
 tensor([[0.5909, 0.0659],
         [0.7476, 0.6253],
         [0.9392, 0.1338]]))

manual seed works only for the next line, ie, line next to it

In [157]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [160]:
tensorGpu = torch.tensor([1,2,3])
tensorGpu.to(device)
tensorGpu.device

device(type='cpu')

can't convert tensor on gpu to numpy

In [161]:
torch.matmul(torch.rand(7,7), torch.rand(1,7).mT)

tensor([[2.2974],
        [1.7910],
        [2.2538],
        [2.2568],
        [2.1363],
        [1.9414],
        [1.4094]])

In [163]:
ten = torch.rand(1,1,1,10)
sqten = torch.squeeze_copy(ten)
ten.shape, sqten.shape

False

##### By default, PyTorch uses a single global RNG. If multiple processes or threads access the RNG simultaneously, it can lead to unpredictable results.

fork_rng creates a separate RNG state for each process/thread, ensuring each one generates its own random number sequence without interfering with others.

You typically use manual_seed to set a global seed for the RNG when you want reproducible results across different runs of your code.
You use fork_rng primarily in multi-process or multi-threaded scenarios to avoid conflicts between different processes/threads accessing the same RNG.
You might use get_rng_state and set_rng_state along with fork_rng for more advanced use cases. For instance, you could save the RNG state at a specific point in your training and later restore it to reproduce that exact state (useful for debugging or resuming training).

pen_spark
